# Generated by Django 5.2.7 on 2026-02-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
    ]
