# Generated by Django 4.2.27 on 2025-12-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singingclass',
            options={},
        ),
    ]
