# Generated by Django 5.2.7 on 2026-02-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_singer_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='seat_numbers',
        ),
    ]
