# Generated by Django 5.2.7 on 2026-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_available_seats_alter_event_basic_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list, help_text="List of seat ids for this booking (e.g. ['vip-1-01','vip-1-02'])."),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats remaining for bookings.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basic ticket price (₹).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='basic_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for Basic tickets (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Premium ticket price (₹).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='premium_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for Premium tickets (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy general ticket price (optional).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_slot',
            field=models.CharField(help_text="Time slot for the event, e.g. '18:00 - 20:00'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, help_text='Total seats for this event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VIP ticket price (₹).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for VIP tickets (optional).', null=True),
        ),
    ]
