# Generated by Django 5.2.7 on 2026-02-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventbooking_seat_numbers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['id'], 'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
    ]
