# Generated by Django 5.2.7 on 2026-02-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_singer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singingclass',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='singingclass',
            name='payment_method',
        ),
    ]
