# Generated by Django 5.2.7 on 2026-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_singingclass_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingclass',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='singingclass',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'NetBanking')], default=1.0, max_length=20),
            preserve_default=False,
        ),
    ]
