# Generated by Django 5.2.7 on 2026-02-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_singingclass_address2_singingclass_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='video_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
