# Generated by Django 5.2.7 on 2026-02-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_singer_video_expiry_date_alter_singer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='video_expiry_date',
        ),
        migrations.AlterField(
            model_name='singer',
            name='created_at',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='singer',
            name='updated_at',
            field=models.DateField(editable=False),
        ),
    ]
