# Generated by Django 5.2.7 on 2026-03-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_singer_video_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographybooking',
            name='payment_methods_list',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='videography',
            name='payment_method',
        ),
    ]
