# Generated by Django 5.2.7 on 2026-03-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_photographybooking_payment_methods_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographybooking',
            name='payment_methods_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sound',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], default='Cash', max_length=10),
        ),
        migrations.AddField(
            model_name='videography',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], default='Cash', max_length=10),
        ),
    ]
