# Generated by Django 5.2.7 on 2026-03-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_photographybooking_payment_methods_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographybooking',
            name='payment_methods_list',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='videography',
            name='payment_method',
        ),
    ]
