# Generated by Django 5.2.7 on 2026-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_photographybooking_payment_methods_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videography',
            name='event_type',
            field=models.CharField(blank=True, choices=[('ALL music events', 'All music events'), ('Birthday', 'Birthday'), ('Other', 'Other')], default='', help_text='Type of event (All music events, , Birthday, Other)', max_length=50),
        ),
    ]
