# Generated by Django 5.2.7 on 2026-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_videography_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videography',
            name='event_type',
            field=models.CharField(blank=True, choices=[('all_music_events', 'All music events'), ('Birthday', 'Birthday'), ('Other', 'Other')], default='', max_length=50),
        ),
    ]
