# Generated by Django 5.2.7 on 2026-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_videography_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videography',
            name='event_type',
            field=models.CharField(blank=True, choices=[('all music events', 'All music events'), ('Birthday', 'Birthday'), ('Other', 'Other')], default='', help_text='Type of event (all music events, Birthday, Other)', max_length=50),
        ),
    ]
