# Generated by Django 5.2.7 on 2026-03-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_videography_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='singingclass',
            name='payment_method',
        ),
    ]
