# Generated by Django 5.2.7 on 2026-03-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_singer_payment_method_remove_singer_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
