# Generated by Django 5.2.7 on 2026-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_singer_payment_method_remove_singer_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualfee',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='annualfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annualfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='annualfee',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='annualfee',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='annualfee',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='annualfee',
            name='year',
        ),
    ]
