# Generated by Django 5.2.7 on 2026-05-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_studio_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingclass',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
