# Generated by Django 5.2.7 on 2026-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_eventbooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
