# Generated by Django 5.2.7 on 2026-06-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_notification_singer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='singingclass',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singingclass',
            name='fee_month_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singingclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
    ]
