# Generated by Django 5.2.7 on 2026-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_singingclass_birth_date_singingclass_fee_month_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
