# Generated by Django 5.2.7 on 2026-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_studio_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiomaster',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
