# Generated by Django 5.2.7 on 2026-06-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_studiomaster_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiomaster',
            name='status',
        ),
    ]
