# Generated by Django 5.2.7 on 2026-06-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_studiomaster_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(db_index=True, max_length=100)),
                ('slot_date', models.DateField(db_index=True)),
                ('slot_time', models.TimeField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slot', to='api.studio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_studio_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studio_slots',
                'ordering': ['slot_date', 'slot_time'],
                'indexes': [models.Index(fields=['studio_name'], name='studio_slot_studio__d9016d_idx'), models.Index(fields=['slot_date'], name='studio_slot_slot_da_21d2a4_idx'), models.Index(fields=['slot_time'], name='studio_slot_slot_ti_f12198_idx'), models.Index(fields=['status'], name='studio_slot_status_bc4f04_idx')],
                'unique_together': {('studio_name', 'slot_date', 'slot_time')},
            },
        ),
    ]
