# Generated by Django 5.2.7 on 2026-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_studioslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='booked', max_length=20),
        ),
    ]
