# Generated by Django 5.2.7 on 2026-06-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_studio_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studioslot',
            name='studio_slot_studio__d9016d_idx',
        ),
        migrations.RemoveIndex(
            model_name='studioslot',
            name='studio_slot_slot_da_21d2a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='studioslot',
            name='studio_slot_slot_ti_f12198_idx',
        ),
        migrations.RemoveIndex(
            model_name='studioslot',
            name='studio_slot_status_bc4f04_idx',
        ),
    ]
