# Generated by Django 5.2.7 on 2026-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_studioslot_studio_slot_studio__d9016d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studioslot',
            index=models.Index(fields=['studio_name'], name='studio_slot_studio__d9016d_idx'),
        ),
        migrations.AddIndex(
            model_name='studioslot',
            index=models.Index(fields=['slot_date'], name='studio_slot_slot_da_21d2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='studioslot',
            index=models.Index(fields=['slot_time'], name='studio_slot_slot_ti_f12198_idx'),
        ),
        migrations.AddIndex(
            model_name='studioslot',
            index=models.Index(fields=['status'], name='studio_slot_status_bc4f04_idx'),
        ),
    ]
