# Generated by Django 5.2.7 on 2026-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_studioslot_studio_slot_studio__d9016d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
