# Generated by Django 5.2.7 on 2026-07-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_studio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='booked', max_length=20),
        ),
    ]
