# Generated by Django 5.2.7 on 2026-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_studio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Payment'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
