# Generated by Django 5.2.7 on 2026-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_studio_payment_status_alter_studio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='booked', max_length=20),
        ),
    ]
