# Generated by Django 5.2.3 on 2026-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_user_fk_to_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
