# Generated by Django 5.2.3 on 2026-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_studio_pending_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('available', 'Available'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
