# Generated by Django 5.2.3 on 2026-07-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_studio_status_choices_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
