# Generated by Django 5.2.7 on 2026-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudioBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField(help_text='Start time of the booking (24h).')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Duration in hours, e.g. 1.0, 1.5, 2.0', max_digits=4)),
                ('payment_methods_csv', models.CharField(blank=True, help_text='Comma-separated payment methods.', max_length=200)),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0, help_text='Final agreed price (total, not per hour).', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User studio booking',
                'verbose_name_plural': 'User studio bookings',
                'ordering': ['-date', '-time_slot', '-created_at'],
            },
        ),
    ]
