# Generated by Django 5.2.7 on 2026-01-30 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Dashboard', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudiobooking',
            name='studio',
            field=models.ForeignKey(help_text='Studio being booked.', on_delete=django.db.models.deletion.PROTECT, related_name='user_bookings', to='api.studiomaster'),
        ),
        migrations.AddField(
            model_name='userstudiobooking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='If the customer is logged in, link the booking to the user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_studio_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
