
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: imc_db
      MYSQL_USER: imc_user
      MYSQL_PASSWORD: imc_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ../Backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../Backend/.env
    volumes:
      - ../Backend:/app   # 🔥 live reload
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    build:
      context: ../Frontend/imc
      dockerfile: Dockerfile.dev
    volumes:
      - ../Frontend/imc:/app
      - /app/node_modules
    ports:
      - "5173:5173"

    # env_file:
    #   - ../Frontend/imc/.env.local

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    command: npm run dev


  phpmyadmin:
      image: phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_USER: imc_user
        PMA_PASSWORD: imc_pass
        MYSQL_ROOT_PASSWORD: root
      ports: 
        - "8080:80"
      restart: always

      depends_on:
        - mysql
  
volumes:
  mysql_data:
