# Generated by Django 5.2.7 on 2026-03-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_raw_response_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('studio_booking', 'Studio Booking'), ('singing_classes', 'Singing Classes'), ('auditorium_music_shows', 'Auditorium Music Shows'), ('private_music_events', 'Private Music Events'), ('photography_service', 'Photography Service'), ('videography_service', 'Videography Service'), ('sound_system_service', 'Sound System Service'), ('singer_management', 'Singer Management')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('CHARGED', 'Charged'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=50),
        ),
    ]
