# Generated by Django 5.2.7 on 2026-03-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_payment_type_payment_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('CHARGED', 'Charged'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
