# Generated by Django 5.2.7 on 2026-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.CharField(blank=True, choices=[('studio_booking', 'Studio Booking'), ('singing_classes', 'Singing Classes'), ('auditorium_music_shows', 'Auditorium Music Shows'), ('private_music_events', 'Private Music Events'), ('photography_service', 'Photography Service')], max_length=100, null=True),
        ),
    ]
