# Generated by Django 5.2.7 on 2026-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.CharField(choices=[('studio_booking', 'Studio Booking'), ('singing_classes', 'Singing Classes'), ('auditorium_music_shows', 'Auditorium Music Shows'), ('private_music_events', 'Private Music Events'), ('photography_service', 'Photography Service')], default=0.1, max_length=100),
            preserve_default=False,
        ),
    ]
