# Generated by Django 5.2.7 on 2026-03-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.CharField(blank=True, choices=[('studio_booking', 'Studio Booking'), ('singing_classes', 'Singing Classes'), ('auditorium_music_shows', 'Auditorium Music Shows'), ('private_music_events', 'Private Music Events'), ('photography_service', 'Photography Service')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('CHARGED', 'Charged'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
