# Generated by Django 5.2.7 on 2026-05-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_singingclass_payment_status'),
        ('payments', '0014_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.singingclass'),
        ),
    ]
