# Generated by Django 5.2.7 on 2026-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='registration',
        ),
        migrations.AddField(
            model_name='payment',
            name='registration_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
