# Generated by Django 5.2.7 on 2026-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_remove_payment_registration_payment_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
