# Generated by Django 5.2.7 on 2026-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_payment_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.CharField(blank=True, choices=[('studio_booking', 'Studio Booking'), ('singing_classes', 'Singing Classes'), ('auditorium_music_shows', 'Auditorium Music Shows'), ('private_music_events', 'Private Music Events'), ('photography_service', 'Photography Service'), ('singer_registration', 'Singer Registration'), ('sound_service', 'Sound Service'), ('videography_service', 'Videography Service')], max_length=100, null=True),
        ),
    ]
